In [1]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# 1. 텐서(Tensor)

In [9]:
# 스칼라(Scalar) - 0차원 텐서
t0 = tf.constant(1) 
print(t0)
print(tf.rank(t0)) # 차원 개수 반환

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [10]:
# 벡터(Vector) - 1차원 텐서
t1 = tf.constant([1, 2, 3]) 
print(t1)
print(tf.rank(t1)) # 차원 개수 반환

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [12]:
# Q. 위 이미지와 같은 크기(3, 3, 3)의 3차원 텐서를 만들고, 차원을 반환해 주세요.
t3 = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

print(t3)
print(t3.shape)        # (3, 3, 3)
print(tf.rank(t3))     # 3

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int32)
(3, 3, 3)
tf.Tensor(3, shape=(), dtype=int32)


# 2. 텐서 타입 및 변환

## 2-1. 타입

In [14]:
# 정수
i = tf.constant(2)
print(i)

tf.Tensor(2, shape=(), dtype=int32)


In [15]:
# 실수
f = tf.constant(2.)
print(f)

tf.Tensor(2.0, shape=(), dtype=float32)


In [16]:
# 문자열
s = tf.constant('Suan')
print(s)

tf.Tensor(b'Suan', shape=(), dtype=string)


In [22]:
# 타입의 수동 지정
i8 = tf.constant(2, dtype=tf.int8)
print(i8)

tf.Tensor(2, shape=(), dtype=int8)


## 2-2. 타입 변환 (tf.cast())

In [32]:
# 정수 ->  문자열 타입으로
string_2 = tf.strings.as_string(i8)
print(string_2)

tf.Tensor(b'2', shape=(), dtype=string)


In [34]:
float_2 = tf.cast(i8, tf.float16)
print(float_2)

tf.Tensor(2.0, shape=(), dtype=float16)


## 2-3. 형상 변환 (tf.reshape())

In [35]:
x = tf.constant([[1], [2], [3]])
print(x)
print(x.shape)

y = tf.reshape(x, [1, 3])
print(y)
print(y.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


## 2-4. 전치 (tf.transpose())

In [36]:
print(y)
print(tf.transpose(y))
print(y.shape)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(1, 3)


## 2-5. 차원 압축 (tf.squeeze())

In [41]:
# 크기가 1인 차원을 삭제함 
print(x)
print(tf.squeeze(x)) #여기선 행이 하나(크기 1) 이므로 행의 차원을 삭제

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


## 2-6. 차원 추가 (tf.expand_dims())

In [42]:
print(y)
print(tf.expand_dims(y, axis=0))
print(tf.expand_dims(y, axis=1))
print(tf.expand_dims(y, axis=2))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


## 2-7. 텐서 분리 (tf.split())

In [43]:
print(x)
print(tf.split(x, 3))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
[<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]])>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]])>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[3]])>]


## 2-8. 텐서 연결 (tf.concat())

In [45]:
print(x)
print(tf.concat([x, x], axis=[0]))
print(tf.concat([x, x], axis=[1]))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)


In [52]:
tensor0 = tf.constant([[1], [2], [3]], dtype=tf.int32)
tensor1 = tf.constant([[5], [6], [7]], dtype=tf.int32)
tensor2 = tf.constant([[8], [9], [10]], dtype=tf.int32)
x3 = tf.concat([tensor0, tensor1, tensor2], axis=1)
print(x3)

tf.Tensor(
[[ 1  5  8]
 [ 2  6  9]
 [ 3  7 10]], shape=(3, 3), dtype=int32)


# 3. 텐서 연산

In [50]:
print(tf.constant(2) + tf.constant(2))
print(tf.constant(2) - tf.constant(2))
print(tf.add(tf.constant(2), tf.constant(2)))
print(tf.subtract(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [51]:
print(tf.constant(2) * tf.constant(2))
print(tf.constant(2) / tf.constant(2))
print(tf.multiply(tf.constant(2), tf.constant(2)))
print(tf.divide(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)


In [53]:
x3 * x3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  1,  25,  64],
       [  4,  36,  81],
       [  9,  49, 100]])>

In [54]:
x3 @ x3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 35,  91, 133],
       [ 41, 109, 160],
       [ 47, 127, 187]])>